contact_links:
  - name: GitHub Community Support
    url: https://github.com/michaeldrotar/tabby/discussions
    about: Please leave your questions here.
  - name: GitHub Security
    url: https://github.com/michaeldrotar/tabby/security
    about: Please report security vulnerabilities here.
